name: Deploy to Amazon EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            
            cd /var/www/app
            
            # 2. Force Git to trust this directory
            git config --global --add safe.directory /var/www/app

            # 3. NUCLEAR OPTION: Discard server changes and match GitHub exactly
            git fetch --all
            git reset --hard origin/master
            
            # 4. Install & Restart
            npm install
            pm2 restart fast-app
